// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSpell(ctx context.Context, arg CreateSpellParams) error
	GetSpellById(ctx context.Context, id uuid.UUID) (Spell, error)
	GetSpellByName(ctx context.Context, name string) (Spell, error)
}

var _ Querier = (*Queries)(nil)
