// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: spells.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpell = `-- name: CreateSpell :one
INSERT INTO spells (
  name,
  element,
  book_id
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, name, element, book_id, updated_at, created_at
`

type CreateSpellParams struct {
	Name    string      `json:"name"`
	Element Element     `json:"element"`
	BookID  pgtype.UUID `json:"book_id"`
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (Spell, error) {
	row := q.db.QueryRow(ctx, createSpell, arg.Name, arg.Element, arg.BookID)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Element,
		&i.BookID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSpell = `-- name: DeleteSpell :exec
DELETE FROM spells
WHERE id = $1
RETURNING id, name, element, book_id, updated_at, created_at
`

func (q *Queries) DeleteSpell(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpell, id)
	return err
}

const getSpellById = `-- name: GetSpellById :one
SELECT id, name, element, book_id, updated_at, created_at
FROM spells
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSpellById(ctx context.Context, id pgtype.UUID) (Spell, error) {
	row := q.db.QueryRow(ctx, getSpellById, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Element,
		&i.BookID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSpellsByBook = `-- name: GetSpellsByBook :many
SELECT id, name, element, book_id, updated_at, created_at
FROM spells
WHERE book_id = $1
`

func (q *Queries) GetSpellsByBook(ctx context.Context, bookID pgtype.UUID) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpellsByBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spell{}
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Element,
			&i.BookID,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpell = `-- name: UpdateSpell :one
UPDATE spells 
SET 
  book_id = CASE WHEN $1::boolean
  THEN $2::uuid ELSE book_id END,
  
  element = CASE WHEN $3::boolean
  THEN $4::element ELSE element END,

  name = CASE WHEN $5::boolean
  THEN $6::text ELSE name END
WHERE
  id = $7 
RETURNING id, name, element, book_id, updated_at, created_at
`

type UpdateSpellParams struct {
	BookIDDoUpdate  bool        `json:"book_id_do_update"`
	BookID          pgtype.UUID `json:"book_id"`
	ElementDoUpdate bool        `json:"element_do_update"`
	Element         Element     `json:"element"`
	NameDoUpdate    bool        `json:"name_do_update"`
	Name            string      `json:"name"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSpell(ctx context.Context, arg UpdateSpellParams) (Spell, error) {
	row := q.db.QueryRow(ctx, updateSpell,
		arg.BookIDDoUpdate,
		arg.BookID,
		arg.ElementDoUpdate,
		arg.Element,
		arg.NameDoUpdate,
		arg.Name,
		arg.ID,
	)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Element,
		&i.BookID,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
